[package]
name = "cosmic-applet-wkeys"
version = "0.1.2"
edition = "2024"

[dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic", features = [
    "applet",
    "tokio",
    "wayland",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
